name: CMake Library Build
on: [push, workflow_dispatch]

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                compiler:
                    - { cc: gcc, cxx: g++ }
                    - { cc: clang, cxx: clang++ }
        env:
            CC: ${{ matrix.cc }}
            CXX: ${{ matrix.cxx }}

        steps:
            - uses: actions/checkout@v3

            - uses: lukka/get-cmake@v3.24.3

            - name: Generate project files using CMake
              shell: bash
              run: cmake -S . -B build

            - name: Build library (Release configuration)
              shell: bash
              run: cmake --build build --config Release

    windows:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-2019, windows-2022]

        steps:
            - uses: actions/checkout@v3

            - uses: lukka/get-cmake@v3.24.3

            - name: Generate project files using CMake
              shell: bash
              run: cmake -S . -B build -G "Visual Studio 16 2019" -A x64
              if: ${{ matrix.os == 'windows-2019' }}

            - name: Generate project files using CMake
              shell: bash
              run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
              if: ${{ matrix.os == 'windows-2022' }}

            - name: Build library (Release configuration)
              shell: bash
              run: cmake --build build --config Release
