name: CMake Library Build
on: [push, workflow_dispatch]

jobs:
    build:
        name: ${{ matrix.config.os }}-${{ matrix.config.cxx }}
        runs-on: ${{ matrix.config.os }}
        strategy:
            matrix:
                config:
                    - {
                        os: ubuntu-latest,
                        cc: gcc,
                        cxx: g++
                    }
                    - {
                        os: ubuntu-latest,
                        cc: clang,
                        cxx: clang++
                    }
                    - {
                        os: windows-latest,
                        cc: cl,
                        cxx: cl
                    }
        env:
            CC: ${{ matrix.config.cc }}
            CXX: ${{ matrix.config.cxx }}

        steps:
            - uses: actions/checkout@v3

            - uses: lukka/get-cmake@v3.24.3

            - name: List working directory content
              shell: bash
              run: find $RUNNER_WORKSPACE

            - name: Run CMake
              uses: docker://lpenz/ghaction-cmake:0.21.1
              with:
                  cmakeflags: '-DCMAKE_BUILD_TYPE=Release'

            - name: List $RUNNER_WORKSPACE after build
              run: find $RUNNER_WORKSPACE
              shell: bash

