name: CMake Library Build
on: [push, workflow_dispatch]

jobs:
    build-linux:
        name: Linux-${{ matrix.compiler[0] }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                compiler:
                    - [gcc, g++]
                    - [clang, clang++]
        env:
            CC: ${{ matrix.compiler[0] }}
            CXX: ${{ matrix.compiler[1] }}

        steps:
            - uses: actions/checkout@v3

            - uses: lukka/get-cmake@v3.24.3
            - name: List working directory content
              shell: bash
              run: |
                find $RUNNER_WORKSPACE
                cmake --version

            - name: Generate project files using CMake
              shell: bash
              run: cmake -S . -B ${{ runner.workspace }}/build

            - name: Build library (Release configuration)
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --config Release

    build-windows:
        name: Windows
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3

            - uses: lukka/get-cmake@v3.24.3
            - name: List working directory content
              run: find $RUNNER_WORKSPACE
              shell: bash

            - name: Generate project files using CMake
              shell: cmake -P {0}
              run: |
                cmake_path(SET build_path ${{ runner.workspace }}/build)
                execute_process(
                    COMMAND cmake
                        -S .
                        -B ${build_path}
                )

            - name: Build library (Release configuration)
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --config Release