name: CMake Library Build
on: [push, workflow_dispatch]

jobs:
    build-lib:
        name: ${{ matrix.os }}-${{ github.workflow }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v3

            - uses: lukka/get-cmake@latest
            - name: List working directory content
              run: find $RUNNER_WORKSPACE
              shell: bash

            - name: Print working directory
              run: pwd
              shell: bash

            - name: Generate project files using CMake
              shell: cmake -P {0}
              run: |
                cmake_path(SET build_path ${{ runner.workspace }}/build)
                execute_process(
                    COMMAND cmake
                        -S .
                        -B ${build_path}
                )

            - name: Build library (Release configuration)
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --config Release

            - name: List $RUNNER_WORKSPACE after build
              run: find $RUNNER_WORKSPACE
              shell: bash